import type {
  Banner,
  Collection,
  Coupon,
  Customer,
  FAQ,
  GiftEnquiry,
  Order,
  Product,
  Review,
  Settings,
} from "./types";

/* Placeholder images — deterministic seeds via picsum for reliable loading.
 * The admin can replace these with real product photos anytime. */
const pic = (seed: string, w = 1200, h = 1500) =>
  `https://picsum.photos/seed/ww-${seed}/${w}/${h}`;

const IMG = {
  hero: pic("hero-candle", 1600, 1900),
  heroAlt: pic("hero-alt", 1600, 1900),
  rose: pic("rose", 1200, 1500),
  rose2: pic("rose-alt", 1200, 1500),
  lavender: pic("lavender", 1200, 1500),
  lavender2: pic("lavender-alt", 1200, 1500),
  jasmine: pic("jasmine", 1200, 1500),
  jasmine2: pic("jasmine-alt", 1200, 1500),
  peony: pic("peony", 1200, 1500),
  peony2: pic("peony-alt", 1200, 1500),
  gift: pic("gift", 1200, 1500),
  gift2: pic("gift-alt", 1200, 1500),
  amber: pic("amber", 1200, 1500),
  vanilla: pic("vanilla", 1200, 1500),
  sandalwood: pic("sandalwood", 1200, 1500),
  interior1: pic("interior-1", 1600, 1200),
  interior2: pic("interior-2", 1600, 1200),
  interior3: pic("interior-3", 1600, 1200),
  florals: pic("florals", 1600, 1200),
  gifting: pic("gifting-scene", 1600, 900),
  studio: pic("studio", 1600, 2000),
  handpour: pic("handpour", 1600, 1200),
  social1: pic("social-1", 800, 800),
  social2: pic("social-2", 800, 800),
  social3: pic("social-3", 800, 800),
  social4: pic("social-4", 800, 800),
  social5: pic("social-5", 800, 800),
  social6: pic("social-6", 800, 800),
};

const products: Product[] = [
  {
    id: "p_rose_bloom",
    slug: "rose-bloom-candle",
    name: "Rose Bloom Candle",
    sku: "WW-RB-220",
    shortDescription: "A soft, dew-kissed rose garden captured in soy wax.",
    description:
      "Rose Bloom opens with fresh petals over green stems and settles into a warm, powdery finish. Hand-poured in small batches, each candle burns cleanly for a slow, generous throw that fills a room without ever feeling heavy.",
    category: "Floral",
    collections: ["best-sellers", "floral", "luxury"],
    images: [
      { url: IMG.rose, alt: "Rose Bloom candle on marble" },
      { url: IMG.rose2, alt: "Rose Bloom candle lit at dusk" },
      { url: IMG.florals, alt: "Fresh rose stems" },
    ],
    mrp: 749,
    price: 599,
    stock: 42,
    lowStockThreshold: 8,
    weightGrams: 220,
    dimensions: "8 × 8 × 9 cm",
    fragrance: "Rose, Green Petals, Musk",
    fragranceNotes: {
      top: ["Dew", "Green leaves"],
      heart: ["Rose petals", "Peony"],
      base: ["Soft musk", "Cedar"],
    },
    waxType: "Soy wax blend",
    burnTimeHours: 45,
    ingredients: ["Soy wax", "Cotton wick", "Rose absolute", "Essential oils"],
    careInstructions: [
      "Trim wick to 5 mm before each burn.",
      "First burn — 2 to 3 hours until the wax pool reaches the edge.",
      "Never leave a candle unattended.",
    ],
    tags: ["rose", "floral", "gifting", "best-seller"],
    status: "active",
    createdAt: "2025-11-02T10:00:00.000Z",
    bestSeller: true,
    newArrival: false,
    rating: 4.8,
    reviewCount: 218,
  },
  {
    id: "p_lavender_calm",
    slug: "lavender-calm-candle",
    name: "Lavender Calm Candle",
    sku: "WW-LC-220",
    shortDescription: "Provencal lavender fields, quieted with vanilla haze.",
    description:
      "A calming, slow-burning candle designed for evenings and long baths. French lavender is softened with a whisper of vanilla and a fine dusting of chamomile, so the room feels held rather than perfumed.",
    category: "Herbal",
    collections: ["best-sellers", "minimal", "luxury"],
    images: [
      { url: IMG.lavender, alt: "Lavender Calm candle" },
      { url: IMG.lavender2, alt: "Lavender Calm styled with linen" },
    ],
    mrp: 749,
    price: 549,
    stock: 18,
    lowStockThreshold: 8,
    weightGrams: 220,
    dimensions: "8 × 8 × 9 cm",
    fragrance: "French Lavender, Vanilla, Chamomile",
    fragranceNotes: {
      top: ["Lavender bud"],
      heart: ["Chamomile", "Sage"],
      base: ["Vanilla", "White amber"],
    },
    waxType: "Soy wax blend",
    burnTimeHours: 45,
    ingredients: ["Soy wax", "Cotton wick", "Lavender essential oil"],
    careInstructions: [
      "Trim wick to 5 mm before each burn.",
      "Burn on a heat-safe surface.",
    ],
    tags: ["lavender", "calm", "best-seller"],
    status: "active",
    createdAt: "2025-10-24T10:00:00.000Z",
    bestSeller: true,
    newArrival: false,
    rating: 4.7,
    reviewCount: 174,
  },
  {
    id: "p_jasmine_luxe",
    slug: "jasmine-luxe-candle",
    name: "Jasmine Luxe Candle",
    sku: "WW-JL-260",
    shortDescription: "Night-blooming jasmine, laced with white tea and amber.",
    description:
      "Our most opulent floral. Jasmine sambac takes centre stage, wrapped in warm amber and a thread of white tea. Poured into a heavy amber glass finished by hand.",
    category: "Floral",
    collections: ["luxury", "floral", "new-arrivals"],
    images: [
      { url: IMG.jasmine, alt: "Jasmine Luxe candle" },
      { url: IMG.jasmine2, alt: "Jasmine bloom close-up" },
      { url: IMG.amber, alt: "Amber glass" },
    ],
    mrp: 899,
    price: 699,
    stock: 26,
    lowStockThreshold: 8,
    weightGrams: 260,
    dimensions: "9 × 9 × 10 cm",
    fragrance: "Jasmine Sambac, White Tea, Amber",
    fragranceNotes: {
      top: ["White tea"],
      heart: ["Jasmine sambac", "Neroli"],
      base: ["Amber", "Sandalwood"],
    },
    waxType: "Coconut-soy blend",
    burnTimeHours: 55,
    ingredients: ["Coconut wax", "Soy wax", "Cotton wick", "Fragrance oils"],
    careInstructions: [
      "First burn — 3 to 4 hours.",
      "Store away from direct sunlight.",
    ],
    tags: ["jasmine", "luxury", "amber"],
    status: "active",
    createdAt: "2026-01-08T10:00:00.000Z",
    bestSeller: false,
    newArrival: true,
    rating: 4.9,
    reviewCount: 92,
  },
  {
    id: "p_peony_flower",
    slug: "peony-flower-candle",
    name: "Peony Flower Candle",
    sku: "WW-PF-180",
    shortDescription: "Pale-pink peonies with a lift of citrus and pear.",
    description:
      "A lighter floral for daytime — pink peonies, pear skin, and a small sun-warmed citrus flourish. Ideal for bedrooms, dressing tables and open kitchens.",
    category: "Floral",
    collections: ["floral", "new-arrivals"],
    images: [
      { url: IMG.peony, alt: "Peony Flower candle" },
      { url: IMG.peony2, alt: "Peony bouquet in vase" },
    ],
    mrp: 649,
    price: 499,
    stock: 5,
    lowStockThreshold: 6,
    weightGrams: 180,
    dimensions: "7 × 7 × 8.5 cm",
    fragrance: "Peony, Pear, Citrus zest",
    fragranceNotes: {
      top: ["Pear", "Bergamot"],
      heart: ["Peony", "Rose petals"],
      base: ["Soft musk"],
    },
    waxType: "Soy wax",
    burnTimeHours: 35,
    ingredients: ["Soy wax", "Cotton wick", "Fragrance oils"],
    careInstructions: ["Trim wick before each burn.", "Burn in a well-ventilated space."],
    tags: ["peony", "floral", "light"],
    status: "active",
    createdAt: "2026-01-14T10:00:00.000Z",
    bestSeller: false,
    newArrival: true,
    rating: 4.6,
    reviewCount: 41,
  },
  {
    id: "p_romantic_gift_set",
    slug: "romantic-gift-set",
    name: "Romantic Gift Set",
    sku: "WW-GS-ROM",
    shortDescription: "Two 120g candles and a matchbook, boxed in linen.",
    description:
      "A gift-ready pairing of Rose Bloom and Jasmine Luxe in a hand-tied linen box, with a long-stem matchbook and a card you can write on. Free personalisation on request.",
    category: "Gifting",
    collections: ["gift-sets", "best-sellers"],
    images: [
      { url: IMG.gift, alt: "Romantic gift set" },
      { url: IMG.gift2, alt: "Gift set styled with roses" },
    ],
    mrp: 1299,
    price: 999,
    stock: 12,
    lowStockThreshold: 6,
    weightGrams: 500,
    dimensions: "22 × 12 × 9 cm",
    fragrance: "Rose + Jasmine pairing",
    fragranceNotes: {
      top: ["Rose", "White tea"],
      heart: ["Jasmine", "Peony"],
      base: ["Amber", "Musk"],
    },
    waxType: "Soy wax blend",
    burnTimeHours: 30,
    ingredients: ["Soy wax", "Cotton wicks", "Rose & jasmine oils"],
    careInstructions: ["Trim wicks before use.", "Enjoy the matches — sparingly."],
    tags: ["gifting", "hamper", "romantic"],
    status: "active",
    createdAt: "2025-12-01T10:00:00.000Z",
    bestSeller: true,
    newArrival: false,
    rating: 4.9,
    reviewCount: 66,
  },
  {
    id: "p_vanilla_hush",
    slug: "vanilla-hush-candle",
    name: "Vanilla Hush Candle",
    sku: "WW-VH-220",
    shortDescription: "Creamy Madagascan vanilla with tonka and warm milk.",
    description:
      "A quiet, cocooning candle for winter evenings and reading nooks. Real Madagascan vanilla is layered with tonka bean and a milky, powdery finish that never turns cloying.",
    category: "Gourmand",
    collections: ["minimal", "luxury"],
    images: [
      { url: IMG.vanilla, alt: "Vanilla Hush candle" },
      { url: IMG.amber, alt: "Amber glass detail" },
    ],
    mrp: 749,
    price: 599,
    stock: 34,
    lowStockThreshold: 8,
    weightGrams: 220,
    dimensions: "8 × 8 × 9 cm",
    fragrance: "Vanilla, Tonka, Warm Milk",
    fragranceNotes: {
      top: ["Warm milk"],
      heart: ["Madagascan vanilla"],
      base: ["Tonka bean", "White amber"],
    },
    waxType: "Soy wax blend",
    burnTimeHours: 45,
    ingredients: ["Soy wax", "Cotton wick", "Vanilla absolute"],
    careInstructions: ["Trim wick before each burn."],
    tags: ["vanilla", "gourmand", "cozy"],
    status: "active",
    createdAt: "2025-11-18T10:00:00.000Z",
    bestSeller: true,
    newArrival: false,
    rating: 4.8,
    reviewCount: 132,
  },
  {
    id: "p_sandalwood_slow",
    slug: "sandalwood-slow-candle",
    name: "Sandalwood Slow Candle",
    sku: "WW-SS-260",
    shortDescription: "Mysore-inspired sandalwood with cedar and vetiver.",
    description:
      "A slow, meditative candle rooted in the calm of temple woods. Sandalwood is grounded with cedar and vetiver for something deeply steady — perfect for study, yoga, and long conversations.",
    category: "Woody",
    collections: ["luxury", "minimal"],
    images: [
      { url: IMG.sandalwood, alt: "Sandalwood Slow candle" },
      { url: IMG.interior2, alt: "Interior scene" },
    ],
    mrp: 899,
    price: 749,
    stock: 22,
    lowStockThreshold: 8,
    weightGrams: 260,
    dimensions: "9 × 9 × 10 cm",
    fragrance: "Sandalwood, Cedar, Vetiver",
    fragranceNotes: {
      top: ["Cedar shavings"],
      heart: ["Sandalwood"],
      base: ["Vetiver", "Warm amber"],
    },
    waxType: "Coconut-soy blend",
    burnTimeHours: 55,
    ingredients: ["Coconut wax", "Soy wax", "Cotton wick"],
    careInstructions: ["First burn — 3 to 4 hours.", "Keep out of drafts."],
    tags: ["sandalwood", "wood", "quiet"],
    status: "active",
    createdAt: "2025-09-04T10:00:00.000Z",
    bestSeller: false,
    newArrival: false,
    rating: 4.7,
    reviewCount: 88,
  },
  {
    id: "p_amber_dusk",
    slug: "amber-dusk-candle",
    name: "Amber Dusk Candle",
    sku: "WW-AD-260",
    shortDescription: "Golden amber, saffron, and a whisper of oud.",
    description:
      "An after-hours candle. Amber and saffron open into a soft, resinous middle before settling into a warm oud finish. Small batch, in heavy amber glass.",
    category: "Amber",
    collections: ["luxury", "best-sellers"],
    images: [
      { url: IMG.amber, alt: "Amber Dusk candle" },
      { url: IMG.interior1, alt: "Interior scene" },
    ],
    mrp: 999,
    price: 849,
    stock: 15,
    lowStockThreshold: 6,
    weightGrams: 260,
    dimensions: "9 × 9 × 10 cm",
    fragrance: "Amber, Saffron, Oud",
    fragranceNotes: {
      top: ["Saffron"],
      heart: ["Amber", "Rose"],
      base: ["Oud", "Sandalwood"],
    },
    waxType: "Coconut-soy blend",
    burnTimeHours: 55,
    ingredients: ["Coconut wax", "Soy wax", "Cotton wick"],
    careInstructions: ["First burn — 3 to 4 hours."],
    tags: ["amber", "oud", "luxury"],
    status: "active",
    createdAt: "2025-08-22T10:00:00.000Z",
    bestSeller: true,
    newArrival: false,
    rating: 4.9,
    reviewCount: 148,
  },
  {
    id: "p_gift_hamper_signature",
    slug: "signature-hamper",
    name: "Signature Hamper",
    sku: "WW-GS-SIG",
    shortDescription: "Three candles, a wick trimmer, and matches in a linen box.",
    description:
      "Our most gifted set. Rose Bloom, Vanilla Hush, and Amber Dusk together with a brass wick trimmer and long-stem matches — arranged in a hand-tied linen box with tissue and a card.",
    category: "Gifting",
    collections: ["gift-sets", "the-occasion-edit"],
    images: [
      { url: IMG.gift2, alt: "Signature hamper" },
      { url: IMG.gift, alt: "Signature hamper open" },
    ],
    mrp: 2199,
    price: 1799,
    stock: 9,
    lowStockThreshold: 4,
    weightGrams: 900,
    dimensions: "30 × 20 × 10 cm",
    fragrance: "Rose, Vanilla, Amber",
    fragranceNotes: {
      top: ["Rose", "Warm milk"],
      heart: ["Vanilla", "Amber"],
      base: ["Musk", "Oud"],
    },
    waxType: "Mixed",
    burnTimeHours: 100,
    ingredients: ["Soy & coconut wax", "Cotton wicks"],
    careInstructions: ["Trim wicks before each burn.", "Store dust cover between uses."],
    tags: ["gifting", "hamper"],
    status: "active",
    createdAt: "2025-10-11T10:00:00.000Z",
    bestSeller: false,
    newArrival: false,
    rating: 5.0,
    reviewCount: 54,
  },
  {
    id: "p_travel_trio",
    slug: "travel-trio",
    name: "Travel Trio (3 × 60g)",
    sku: "WW-TR-60",
    shortDescription: "Three miniature candles for weekends and stays.",
    description:
      "A little edit of our three most-loved fragrances at travel size — Rose Bloom, Lavender Calm and Amber Dusk. Ideal for suitcases, gift stacks and first-time try-ons.",
    category: "Gifting",
    collections: ["gift-sets", "new-arrivals"],
    images: [
      { url: IMG.gift, alt: "Travel trio" },
      { url: IMG.interior3, alt: "Travel scene" },
    ],
    mrp: 899,
    price: 749,
    stock: 0,
    lowStockThreshold: 4,
    weightGrams: 180,
    dimensions: "18 × 6 × 6 cm",
    fragrance: "Rose, Lavender, Amber",
    fragranceNotes: {
      top: ["Petals"],
      heart: ["Lavender"],
      base: ["Amber"],
    },
    waxType: "Soy wax blend",
    burnTimeHours: 60,
    ingredients: ["Soy wax", "Cotton wicks"],
    careInstructions: ["Small candles — never leave unattended."],
    tags: ["travel", "trio", "gifting"],
    status: "out_of_stock",
    createdAt: "2026-01-19T10:00:00.000Z",
    bestSeller: false,
    newArrival: true,
    rating: 4.7,
    reviewCount: 22,
  },
];

const collections: Collection[] = [
  {
    id: "c_best_sellers",
    slug: "best-sellers",
    title: "Best Sellers",
    subtitle: "Loved most, gifted often",
    description: "The candles our community reaches for again and again.",
    image: IMG.interior1,
    featured: true,
    productIds: [
      "p_rose_bloom",
      "p_lavender_calm",
      "p_amber_dusk",
      "p_vanilla_hush",
      "p_romantic_gift_set",
    ],
  },
  {
    id: "c_new_arrivals",
    slug: "new-arrivals",
    title: "New Arrivals",
    subtitle: "Freshly poured this season",
    description: "The latest additions to the White & Wick library.",
    image: IMG.jasmine,
    featured: true,
    productIds: ["p_jasmine_luxe", "p_peony_flower", "p_travel_trio"],
  },
  {
    id: "c_floral",
    slug: "floral",
    title: "Floral Collection",
    subtitle: "A garden in a jar",
    description: "Peonies, jasmine, and roses — softly interpreted for the home.",
    image: IMG.florals,
    featured: true,
    productIds: ["p_rose_bloom", "p_jasmine_luxe", "p_peony_flower"],
  },
  {
    id: "c_luxury",
    slug: "luxury",
    title: "Luxury Collection",
    subtitle: "Slow burns, richer notes",
    description: "Deeper fragrances, heavier glass, longer evenings.",
    image: IMG.amber,
    featured: true,
    productIds: [
      "p_amber_dusk",
      "p_jasmine_luxe",
      "p_sandalwood_slow",
      "p_vanilla_hush",
    ],
  },
  {
    id: "c_minimal",
    slug: "minimal",
    title: "Minimal Collection",
    subtitle: "Quiet, uncomplicated candles",
    description: "Everyday scents that ask very little of a room.",
    image: IMG.interior2,
    featured: false,
    productIds: ["p_lavender_calm", "p_vanilla_hush", "p_sandalwood_slow"],
  },
  {
    id: "c_gift_sets",
    slug: "gift-sets",
    title: "Gift Sets",
    subtitle: "Ready to give",
    description: "Boxed, ribboned, and ready with a hand-written card.",
    image: IMG.gift2,
    featured: true,
    productIds: ["p_romantic_gift_set", "p_gift_hamper_signature", "p_travel_trio"],
  },
  {
    id: "c_occasion_edit",
    slug: "the-occasion-edit",
    title: "The Occasion Edit",
    subtitle: "Picked for the moments that matter",
    description:
      "Weddings, anniversaries, birthdays, housewarmings — a curated edit for every occasion, ready to gift.",
    image: IMG.gifting,
    featured: true,
    productIds: [],
  },
  {
    id: "c_occ_friendship",
    slug: "friendship-day",
    title: "Friendship Day",
    subtitle: "For your favourite people",
    description: "Playful hampers and warm scents for the friends who feel like family.",
    image: IMG.social1,
    featured: false,
    productIds: [],
    parentSlug: "the-occasion-edit",
  },
  {
    id: "c_occ_diwali",
    slug: "diwali",
    title: "Diwali",
    subtitle: "A little light, beautifully packed",
    description:
      "Warm, festive candles and hampers for Diwali gifting — for family, teams, and neighbours.",
    image: IMG.interior1,
    featured: false,
    productIds: [],
    parentSlug: "the-occasion-edit",
  },
  {
    id: "c_occ_rakhi",
    slug: "rakhi",
    title: "Rakhi",
    subtitle: "For the sibling who has everything",
    description:
      "Small, considered candle hampers for Rakhi — with hand-written cards and free gift-wrap.",
    image: IMG.gift,
    featured: false,
    productIds: [],
    parentSlug: "the-occasion-edit",
  },
  {
    id: "c_occ_anniversary",
    slug: "anniversary",
    title: "Anniversary",
    subtitle: "A soft, considered gesture",
    description:
      "Romantic pairings and slow-burn candles for anniversaries and first-year milestones.",
    image: IMG.florals,
    featured: false,
    productIds: [],
    parentSlug: "the-occasion-edit",
  },
  {
    id: "c_gs_birthdays",
    slug: "birthday-gifts",
    title: "Birthdays",
    subtitle: "Wish them well, warmly",
    description: "Bright, cheerful candle hampers to send with a hand-written card.",
    image: IMG.peony,
    featured: false,
    productIds: [],
    parentSlug: "gift-sets",
  },
  {
    id: "c_gs_anniversaries",
    slug: "anniversary-gifts",
    title: "Anniversaries",
    subtitle: "Marking the years, softly",
    description:
      "Romantic pairings and slow-burn candles for anniversaries and first-year milestones.",
    image: IMG.rose,
    featured: false,
    productIds: [],
    parentSlug: "gift-sets",
  },
  {
    id: "c_gs_weddings",
    slug: "wedding-gifts",
    title: "Weddings",
    subtitle: "For the couple, from you",
    description:
      "Considered candle hampers for weddings — with custom labels and free gift-wrap.",
    image: IMG.jasmine,
    featured: false,
    productIds: [],
    parentSlug: "gift-sets",
  },
  {
    id: "c_gs_friendship",
    slug: "friendship-gifts",
    title: "Friendship",
    subtitle: "For your favourite people",
    description: "Playful hampers and warm scents for the friends who feel like family.",
    image: IMG.social1,
    featured: false,
    productIds: [],
    parentSlug: "gift-sets",
  },
  {
    id: "c_gs_festive",
    slug: "festive-gifts",
    title: "Festive",
    subtitle: "Diwali, Rakhi & every festival in between",
    description:
      "Warm, festive candles and hampers for the season of giving — for family, teams, and neighbours.",
    image: IMG.amber,
    featured: false,
    productIds: [],
    parentSlug: "gift-sets",
  },
];

const customers: Customer[] = [
  {
    id: "cus_ananya",
    name: "Ananya Sharma",
    email: "ananya.sharma@example.com",
    phone: "+91 98111 22334",
    ordersCount: 4,
    totalSpend: 5296,
    lastOrderAt: "2026-08-14T09:12:00.000Z",
    addresses: [
      {
        id: "a1",
        label: "Home",
        line1: "B-12, Rose Apartments",
        area: "Vasant Kunj",
        city: "New Delhi",
        state: "Delhi",
        pincode: "110070",
      },
    ],
    createdAt: "2025-06-14T09:12:00.000Z",
  },
  {
    id: "cus_meera",
    name: "Meera Iyer",
    email: "meera.iyer@example.com",
    phone: "+91 98890 11223",
    ordersCount: 2,
    totalSpend: 2148,
    lastOrderAt: "2026-08-05T12:33:00.000Z",
    addresses: [
      {
        id: "a1",
        label: "Home",
        line1: "9, Neelkanth Villas",
        area: "Kilpauk",
        city: "Chennai",
        state: "Tamil Nadu",
        pincode: "600010",
      },
    ],
    createdAt: "2025-11-02T09:12:00.000Z",
  },
  {
    id: "cus_rhea",
    name: "Rhea Kapoor",
    email: "rhea.kapoor@example.com",
    phone: "+91 90099 11223",
    ordersCount: 6,
    totalSpend: 8890,
    lastOrderAt: "2026-08-18T12:33:00.000Z",
    addresses: [
      {
        id: "a1",
        label: "Home",
        line1: "22, Peddar Road",
        area: "Cumballa Hill",
        city: "Mumbai",
        state: "Maharashtra",
        pincode: "400026",
      },
    ],
    createdAt: "2024-11-02T09:12:00.000Z",
  },
  {
    id: "cus_ishaan",
    name: "Ishaan Verma",
    email: "ishaan.verma@example.com",
    phone: "+91 98222 33445",
    ordersCount: 1,
    totalSpend: 749,
    lastOrderAt: "2026-08-20T12:33:00.000Z",
    addresses: [],
    createdAt: "2026-08-20T09:12:00.000Z",
  },
  {
    id: "cus_priyanka",
    name: "Priyanka Nair",
    email: "priyanka.nair@example.com",
    phone: "+91 97555 88221",
    ordersCount: 3,
    totalSpend: 3697,
    lastOrderAt: "2026-08-12T12:33:00.000Z",
    addresses: [],
    createdAt: "2025-04-02T09:12:00.000Z",
  },
];

const orders: Order[] = [
  {
    id: "o_1",
    orderNumber: "WW-1042",
    customerId: "cus_rhea",
    customerName: "Rhea Kapoor",
    createdAt: "2026-08-21T09:12:00.000Z",
    items: [
      { productId: "p_amber_dusk", name: "Amber Dusk Candle", image: IMG.amber, qty: 1, price: 849 },
      { productId: "p_romantic_gift_set", name: "Romantic Gift Set", image: IMG.gift, qty: 1, price: 999 },
    ],
    subtotal: 1848,
    discount: 200,
    shipping: 0,
    total: 1648,
    paymentStatus: "paid",
    orderStatus: "processing",
    coupon: "WELCOME10",
    address: {
      name: "Rhea Kapoor",
      phone: "+91 90099 11223",
      line1: "22, Peddar Road",
      area: "Cumballa Hill",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400026",
    },
    giftMessage: "For our anniversary — R",
  },
  {
    id: "o_2",
    orderNumber: "WW-1041",
    customerId: "cus_ananya",
    customerName: "Ananya Sharma",
    createdAt: "2026-08-20T09:12:00.000Z",
    items: [{ productId: "p_rose_bloom", name: "Rose Bloom Candle", image: IMG.rose, qty: 2, price: 599 }],
    subtotal: 1198,
    discount: 0,
    shipping: 0,
    total: 1198,
    paymentStatus: "paid",
    orderStatus: "shipped",
    address: {
      name: "Ananya Sharma",
      phone: "+91 98111 22334",
      line1: "B-12, Rose Apartments",
      area: "Vasant Kunj",
      city: "New Delhi",
      state: "Delhi",
      pincode: "110070",
    },
  },
  {
    id: "o_3",
    orderNumber: "WW-1040",
    customerId: "cus_ishaan",
    customerName: "Ishaan Verma",
    createdAt: "2026-08-20T05:12:00.000Z",
    items: [{ productId: "p_sandalwood_slow", name: "Sandalwood Slow Candle", image: IMG.sandalwood, qty: 1, price: 749 }],
    subtotal: 749,
    discount: 0,
    shipping: 60,
    total: 809,
    paymentStatus: "pending",
    orderStatus: "new",
    address: {
      name: "Ishaan Verma",
      phone: "+91 98222 33445",
      line1: "301, Silver Wave Apartments",
      area: "Powai",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400076",
    },
  },
  {
    id: "o_4",
    orderNumber: "WW-1039",
    customerId: "cus_meera",
    customerName: "Meera Iyer",
    createdAt: "2026-08-18T05:12:00.000Z",
    items: [
      { productId: "p_vanilla_hush", name: "Vanilla Hush Candle", image: IMG.vanilla, qty: 1, price: 599 },
      { productId: "p_lavender_calm", name: "Lavender Calm Candle", image: IMG.lavender, qty: 1, price: 549 },
    ],
    subtotal: 1148,
    discount: 0,
    shipping: 0,
    total: 1148,
    paymentStatus: "paid",
    orderStatus: "delivered",
    address: {
      name: "Meera Iyer",
      phone: "+91 98890 11223",
      line1: "9, Neelkanth Villas",
      area: "Kilpauk",
      city: "Chennai",
      state: "Tamil Nadu",
      pincode: "600010",
    },
  },
  {
    id: "o_5",
    orderNumber: "WW-1038",
    customerId: "cus_priyanka",
    customerName: "Priyanka Nair",
    createdAt: "2026-08-15T05:12:00.000Z",
    items: [{ productId: "p_gift_hamper_signature", name: "Signature Hamper", image: IMG.gift2, qty: 1, price: 1799 }],
    subtotal: 1799,
    discount: 100,
    shipping: 0,
    total: 1699,
    paymentStatus: "paid",
    orderStatus: "delivered",
    coupon: "FIRSTORDER",
    address: {
      name: "Priyanka Nair",
      phone: "+91 97555 88221",
      line1: "44, Marine Lane",
      area: "Kochi",
      city: "Kochi",
      state: "Kerala",
      pincode: "682001",
    },
  },
  {
    id: "o_6",
    orderNumber: "WW-1037",
    customerId: "cus_rhea",
    customerName: "Rhea Kapoor",
    createdAt: "2026-08-08T05:12:00.000Z",
    items: [{ productId: "p_peony_flower", name: "Peony Flower Candle", image: IMG.peony, qty: 1, price: 499 }],
    subtotal: 499,
    discount: 0,
    shipping: 60,
    total: 559,
    paymentStatus: "refunded",
    orderStatus: "cancelled",
    address: {
      name: "Rhea Kapoor",
      phone: "+91 90099 11223",
      line1: "22, Peddar Road",
      area: "Cumballa Hill",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400026",
    },
  },
];

const coupons: Coupon[] = [
  {
    id: "cp_welcome10",
    code: "WELCOME10",
    type: "percent",
    value: 10,
    minOrder: 599,
    maxDiscount: 300,
    usageLimit: 500,
    perCustomerLimit: 1,
    usedCount: 127,
    active: true,
  },
  {
    id: "cp_firstorder",
    code: "FIRSTORDER",
    type: "fixed",
    value: 100,
    minOrder: 999,
    usageLimit: 300,
    perCustomerLimit: 1,
    usedCount: 42,
    active: true,
  },
  {
    id: "cp_gift20",
    code: "GIFT20",
    type: "percent",
    value: 20,
    minOrder: 1499,
    maxDiscount: 500,
    usageLimit: 100,
    usedCount: 12,
    collectionIds: ["c_gift_sets"],
    active: true,
  },
  {
    id: "cp_summer",
    code: "SUMMER",
    type: "percent",
    value: 15,
    minOrder: 799,
    usageLimit: 200,
    usedCount: 200,
    active: false,
  },
];

const banners: Banner[] = [
  {
    id: "b_1",
    title: "The Floral Edit is here",
    subtitle: "Rose, peony and jasmine — softly poured for spring.",
    image: IMG.florals,
    link: "/collections/floral",
    cta: "Shop the edit",
    active: true,
    order: 1,
  },
  {
    id: "b_2",
    title: "Gifting, thought through",
    subtitle: "Hampers for weddings, moving-in and thank-yous.",
    image: IMG.gifting,
    link: "/gifting",
    cta: "Explore gifting",
    active: true,
    order: 2,
  },
];

const reviews: Review[] = [
  {
    id: "r_1",
    productId: "p_rose_bloom",
    customerName: "Aditi R.",
    rating: 5,
    title: "Like a small garden in the living room",
    body: "This is now the third one I've bought. The throw is generous without being loud, and it stays true from start to end.",
    createdAt: "2026-07-20T05:12:00.000Z",
    approved: true,
  },
  {
    id: "r_2",
    productId: "p_lavender_calm",
    customerName: "Kabir S.",
    rating: 5,
    title: "Perfect after a long day",
    body: "Lights every evening at 8 for a bath. It's genuinely calming — not soapy at all.",
    createdAt: "2026-07-08T05:12:00.000Z",
    approved: true,
  },
  {
    id: "r_3",
    productId: "p_amber_dusk",
    customerName: "Nikita P.",
    rating: 5,
    title: "A grown-up amber",
    body: "The saffron opens beautifully. Very slow burn. Bought two more for my sister's wedding.",
    createdAt: "2026-06-30T05:12:00.000Z",
    approved: true,
  },
  {
    id: "r_4",
    productId: "p_jasmine_luxe",
    customerName: "Rhea K.",
    rating: 5,
    title: "This is *the* jasmine",
    body: "I've tried a lot. This one actually smells like jasmine and not perfume. Beautifully packaged.",
    createdAt: "2026-08-01T05:12:00.000Z",
    approved: true,
  },
  {
    id: "r_5",
    productId: "p_vanilla_hush",
    customerName: "Ananya S.",
    rating: 4,
    title: "Cozy",
    body: "Very cozy, warm and milky. Not overly sweet. Repurchased.",
    createdAt: "2026-07-01T05:12:00.000Z",
    approved: true,
  },
];

const faqs: FAQ[] = [
  {
    id: "f_1",
    question: "How long will my candle burn?",
    answer:
      "Our 180g candles burn for roughly 35 hours; 220g candles for around 45 hours; and the 260g Luxury Collection for around 55 hours — provided you trim the wick and let each burn reach the glass edge.",
    category: "Product",
    order: 1,
  },
  {
    id: "f_2",
    question: "Do you ship pan-India?",
    answer:
      "Yes. We ship across India within 3–6 business days. Orders above ₹999 ship free.",
    category: "Shipping",
    order: 2,
  },
  {
    id: "f_3",
    question: "Are your candles handmade?",
    answer:
      "Every White & Wick candle is hand-poured in small batches in our studio, using a soy-and-coconut wax blend and clean-burning cotton wicks.",
    category: "Product",
    order: 3,
  },
  {
    id: "f_4",
    question: "Can I customise a gift hamper?",
    answer:
      "Yes. Head to our Gifting page and fill out the enquiry — we'll come back to you within a working day with a proposal and photos.",
    category: "Gifting",
    order: 4,
  },
  {
    id: "f_5",
    question: "What is your returns policy?",
    answer:
      "For hygiene reasons we can't accept returns on candles that have been burned. Unopened, unused candles can be returned within 7 days of delivery.",
    category: "Returns",
    order: 5,
  },
];

const giftEnquiries: GiftEnquiry[] = [
  {
    id: "g_1",
    name: "Aparna Menon",
    email: "aparna@example.com",
    phone: "+91 98111 00223",
    occasion: "Wedding",
    budget: "₹500 per hamper",
    quantity: "120",
    fragrance: "Rose + Vanilla",
    candle: "Rose Bloom + Vanilla Hush",
    message: "Custom label with couple's initials.",
    additional: "Delivery in Bengaluru by 10 Sep.",
    createdAt: "2026-08-19T05:12:00.000Z",
    status: "new",
  },
  {
    id: "g_2",
    name: "Karan Vij (Zenova Co.)",
    email: "karan@zenovaco.example",
    phone: "+91 98002 44311",
    occasion: "Corporate — Diwali",
    budget: "₹1200 per hamper",
    quantity: "300",
    fragrance: "Sandalwood + Amber",
    candle: "Sandalwood Slow + Amber Dusk",
    message: "Include company card. Discreet branding on box.",
    additional: "Delivery to Gurgaon office by 20 Oct.",
    createdAt: "2026-08-15T05:12:00.000Z",
    status: "in_progress",
  },
];

const settings: Settings = {
  freeShippingAbove: 999,
  currency: "INR",
  announcementBar:
    "Hand-poured with love • Free shipping above ₹999 • Complimentary gift-wrap on hampers",
  socials: {
    instagram: "https://instagram.com/whiteandwick",
    whatsapp: "https://wa.me/919999999999",
    pinterest: "https://pinterest.com/whiteandwick",
  },
  contact: {
    email: "hello@whiteandwick.co",
    phone: "+91 99999 99999",
    address: "Studio 4, Bandra West, Mumbai 400050, India",
  },
  homepage: {
    heroHeading: "Light something\nbeautiful.",
    heroSubheading:
      "Hand-poured scented candles for slow mornings, warm evenings, and everything in between.",
    heroImage: IMG.hero,
    heroCtaLabel: "Shop Candles",
    heroCtaHref: "/shop",
    secondaryCtaLabel: "Explore Gifting",
    secondaryCtaHref: "/gifting",
  },
};

export const seed = {
  products,
  collections,
  customers,
  orders,
  coupons,
  banners,
  reviews,
  faqs,
  giftEnquiries,
  settings,
};

export { IMG };
